# This composer brings up a local Elasticsearch and a local Kibana,
# both persisted at the directory ./_es. This is good for local development.
# To talk to the live service, use es-bridge.sh.
version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    volumes:
      - _es:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - '9200:9200'
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    container_name: kibana
    networks:
      - esnet
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
volumes:
  _es:
    driver: local
networks:
  esnet:
    driver: bridge

